version: "3"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Montando o script de inicialização
    environment:
      POSTGRES_PASSWORD: ma123456
    ports:
      - 5432:5432

volumes:
  pgdata:
